version: '3.4'

networks:
  ysc-net:
    external:
      name: ysc-net
services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: reverse-proxy-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ysc-net
    ports:
      - '80:80'
    depends_on:
      - chessserver
      - middleware
      - stockfishserver
      - chessclient
      - ystemandchess
  chessserver:
    image: chessserver
    container_name: chessserver
    environment:
      - PORT=3000
    networks:
      - ysc-net
    expose:
      - '3000'
    volumes:
      - ../chessServer:/usr/src/app
  chessclient:
    image: chessclient
    container_name: chessclient
    environment:
      - PARENT=ystemandchess
    networks:
      - ysc-net
    expose:
      - '80'
    volumes:
      - ../chessClient:/usr/share/nginx/html
  stockfishserver:
    image: stockfishserver
    container_name: stockfishserver
    environment:
      - PORT=8080
    networks:
      - ysc-net
    expose:
      - '8080'
    volumes:
      - ../stockfishServer:/usr/src/app
  middleware:
    image: middleware
    container_name: middleware
    environment:
      - PORT=8000
      - indexKey=4F15D94B7A5CF347A36FC1D85A3B487D8B4F596FB62C51EFF9E518E433EA4C8C
      - awsAccessKey=AKIA3W5HAAMI23BHM5JP
      - awsSecretKey=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
      - mongoURI=mongodb+srv://userAdmin2:Ap4OoVnQX4ovWrfy@cluster0-rxbrl.mongodb.net/ystem?retryWrites=true&w=majority
      - appID=6c368b93b82a4b3e9fb8e57da830f2a4
      - auth=Basic OTE3ZTZlOTlmODgxNDEwYWI2ZjEyNmY3ZTJiMWM5MDc6NWYwMTU0MTIwMmM3NDYzNzhjZTQ3Nzg3NTljYzg4NGE=
      - channel=10000
      - uid=123
      - jwtSecret=*ystemandchess
    networks:
      - ysc-net
    expose:
      - '8000'
    volumes:
      - ../middleware:/var/www/html
  ystemandchess:
    image: ystemandchess
    container_name: ystemandchess
    networks:
      - ysc-net
    ports:
      - '80'
    depends_on:
      - middleware
      - stockfishserver
      - chessclient
      - chessserver
    volumes:
      - ../YStemAndChess:/usr/src/app/
      - /usr/src/app/node_modules
